.TH nfprofile 1 2009-09-09 "" ""
.SH NAME
nfprofile \- netflow profiler
.SH SYNOPSIS
.HP 5
.B nfprofile [options] 
.SH DESCRIPTION
.B nfprofile
is the netflow profiler program for NfSen.
It reads the netflow data from the files stored by nfcapd and creates
the corresponding output files for every channel required.
This program is run only by NfSen.

.SH OPTIONS

.SH "RETURN VALUE"

.SH NOTES
none.

.SH "SEE ALSO"
nfcapd(1), nfdump(1), nfreplay(1)
.SH BUGS

