#!/bin/sh
#  This file is part of the nfdump project.
#
#  Copyright (c) 2023, Peter Haag
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#   * Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#   * Neither the name of Peter Haag nor the names of its contributors may be
#     used to endorse or promote products derived from this software without
#     specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
# nfcapd regression test suite.
# Tests: pcap file mode (v5/v9/IPFIX/NSEL/CGNAT/timeflows),
#        YAF file mode, compression variants, extension filtering,
#        live network round-trip (v9 and v5), AppendRename, memory guards,
#        post-decode record filter (-F).
#
# Portability: POSIX sh; tested on Linux, *BSD, macOS.
#   'local' is used in helpers — supported by all modern /bin/sh implementations
#   (bash, dash, ksh88+, zsh, busybox ash) even though not in POSIX:2017.
#
# pcap/YAF tests require nfcapd compiled with --enable-readpcap.
# Live round-trip tests require nfreplay and dummy_flows.nf (generated by
# runprepare.sh / nfgen4 during 'make check').

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/testsetup.sh"

# ── helpers ───────────────────────────────────────────────────────────────────

# count_flows FILE
# Reads the statistics block written by nfcapd (-I flag).  This is immune to
# the verbose debug lines that nfdump may print on stdout in devel builds.
count_flows() {
    "$NFDUMP_BIN" -G none -I -r "$1" "$2" 2>/dev/null \
        | awk '/^Flows:/{s += $2} END{print s+0}'
}

# count_exporter_flows FILE
# Sum the cumulative per-exporter flow counts from the exporter metadata block.
count_exporter_flows() {
    "$NFDUMP_BIN" -E "$1" 2>/dev/null \
        | awk -F'flows: ' '/^SysID:/{split($2,a," "); s += a[1]} END{print s+0}'
}

# wait_stop PIDFILE [SECONDS]
wait_stop() {
    local pf="$1" max="${2:-5}" i=0
    while [ -f "$pf" ] && [ "$i" -lt "$max" ]; do
        sleep 1; i=$((i+1))
    done
}

# count_records FILE [FILTER...]
# Reads the actual stored records (via a real record read), not the
# pre-aggregated stats block that count_flows()/-I reads. This matters for
# -F post-filter tests specifically: the filter stage compacts records out of
# each block. The filter stage also rewrites cycle_message_t::stat_record, but
# this direct record count remains the reference for filter-parity checks.
# With no FILTER, returns the number of records physically present in FILE.
# With a FILTER, applies it at nfdump read-time and returns how many match —
# used to derive filter-parity ground truth from an unfiltered baseline file.
count_records() {
    local file="$1"; shift
    "$NFDUMP_BIN" -G none -r "$file" -o null "$@" 2>/dev/null \
        | awk -F'passed: ' '/^Total records processed:/{split($2,a,","); print a[1]+0}'
}

# run_pcap_filter NAME PCAPFILE IDENT FILTER EXPECTED
# Collects PCAPFILE through nfcapd with -F FILTER and checks the actual
# stored record count (count_records, not count_flows) against EXPECTED.
run_pcap_filter() {
    local name="$1" pcap="$2" ident="$3" filter="$4" expected="$5"
    local d="$WORKDIR/$name"
    mkdir -p "$d"
    nfcapd -f "$pcap" -w "$d" -I "$ident" -F "$filter" -v 0 >/dev/null 2>&1
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        fail "$name: nfcapd exited with status $rc"
        return
    fi
    local f
    f=$(ls "$d"/nfcapd.* 2>/dev/null | head -1)
    if [ -z "$f" ]; then
        fail "$name: no output file created"
        return
    fi
    local got
    got=$(count_records "$f")
    if [ "${got:-0}" -eq "$expected" ]; then
        pass "$name: $got records"
    else
        fail "$name: expected $expected records, got ${got:-0}"
    fi
}

# ── pcap file-mode test ───────────────────────────────────────────────────────
# run_pcap NAME PCAPFILE IDENT EXPECTED [extra nfcapd args…]
run_pcap() {
    local name="$1" pcap="$2" ident="$3" expected="$4"
    shift 4
    local d="$WORKDIR/$name"
    mkdir -p "$d"
    nfcapd -f "$pcap" -w "$d" -I "$ident" "$@" -v 0 >/dev/null 2>&1
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        fail "$name: nfcapd exited with status $rc"
        return
    fi
    local f
    f=$(ls "$d"/nfcapd.* 2>/dev/null | head -1)
    if [ -z "$f" ]; then
        fail "$name: no output file created"
        return
    fi
    local got
    got=$(count_flows "$f")
    if [ "${got:-0}" -eq "$expected" ]; then
        pass "$name: $got flows"
    else
        fail "$name: expected $expected flows, got ${got:-0}"
    fi
}

# ── YAF file-mode test ────────────────────────────────────────────────────────
# run_yaf NAME YAFFILE IDENT EXPECTED
run_yaf() {
    local name="$1" yaf="$2" ident="$3" expected="$4"
    local d="$WORKDIR/$name"
    mkdir -p "$d"
    nfcapd -Y "$yaf" -w "$d" -I "$ident" -v 0 >/dev/null 2>&1
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        fail "$name: nfcapd exited with status $rc"
        return
    fi
    local f
    f=$(ls "$d"/nfcapd.* 2>/dev/null | head -1)
    if [ -z "$f" ]; then
        fail "$name: no output file created"
        return
    fi
    local got
    got=$(count_flows "$f")
    if [ "${got:-0}" -eq "$expected" ]; then
        pass "$name: $got flows"
    else
        fail "$name: expected $expected flows, got ${got:-0}"
    fi
}

# =============================================================================
# Prerequisite checks
# =============================================================================
echo ""
echo "── prerequisites ────────────────────────────────────────────────────────"
PREREQ_OK=1

if [ ! -x "$NFCAPD_BIN" ]; then
    echo "  ERROR: nfcapd not found: $NFCAPD_BIN"; PREREQ_OK=0; fi
if [ ! -x "$NFDUMP_BIN" ]; then
    echo "  ERROR: nfdump not found: $NFDUMP_BIN";  PREREQ_OK=0; fi
if [ -z "$TESTDATA" ] || [ ! -d "$TESTDATA" ]; then
    echo "  ERROR: test data directory not found (expected test/nfcapd/)"; PREREQ_OK=0; fi

if [ "$PREREQ_OK" -eq 0 ]; then
    echo "  Skip test: missing prerequisites."
    exit 0
fi

# Detect whether nfcapd was compiled with --enable-readpcap.
# Without it, the -f (pcap) and -Y (yaf) flags are absent from the help text.
HAS_PCAP=0
"$NFCAPD_BIN" -h 2>&1 | grep -q '\-f pcapfile' && HAS_PCAP=1

echo "  nfcapd:   $NFCAPD_BIN"
echo "  nfdump:   $NFDUMP_BIN"
echo "  testdata: $TESTDATA"
if [ "$HAS_PCAP" -eq 1 ]; then
    echo "  pcap/YAF: yes"
else
    echo "  pcap/YAF: no  (pcap/YAF/compression/extension/memck sections skipped)"
    echo "            Rebuild with: ./configure --enable-readpcap"
fi

# =============================================================================
# 1. pcap file mode
# =============================================================================
echo ""
echo "── pcap file mode ───────────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    for _t in pcap_v5_unsamp pcap_v5_samp pcap_v9_unsamp pcap_v9_samp \
              pcap_ipfix_unsamp pcap_ipfix_samp pcap_nsel pcap_cgnat pcap_timeflows; do
        skip "$_t: --enable-readpcap not compiled in"
    done
else
    # Expected counts measured with 'nfdump -I -r <file>' (statistics block).
    run_pcap  pcap_v5_unsamp     "$TESTDATA/flows_v5_unsamp.pcap"    v5_unsamp    159
    run_pcap  pcap_v5_samp       "$TESTDATA/flows_v5_samp.pcap"      v5_samp       34
    run_pcap  pcap_v9_unsamp     "$TESTDATA/flows_v9_unsamp.pcap"    v9_unsamp    161
    run_pcap  pcap_v9_samp       "$TESTDATA/flows_v9_samp.pcap"      v9_samp       35
    run_pcap  pcap_ipfix_unsamp  "$TESTDATA/flows_ipfix_unsamp.pcap" ipfix_unsamp 161
    run_pcap  pcap_ipfix_samp    "$TESTDATA/flows_ipfix_samp.pcap"   ipfix_samp    35
    run_pcap  pcap_nsel          "$TESTDATA/nsel.pcap"               nsel         733447
    run_pcap  pcap_cgnat         "$TESTDATA/CGNAT-ifvrf.pcap"        cgnat        15136
    run_pcap  pcap_timeflows     "$TESTDATA/timeflows.pcap"          timeflows        6
fi

# =============================================================================
# 2. YAF file mode
# =============================================================================
echo ""
echo "── YAF file mode ────────────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    skip "yaf_flows:   --enable-readpcap not compiled in"
    skip "yaf_flows_2: --enable-readpcap not compiled in"
else
    run_yaf  yaf_flows   "$TESTDATA/flows.yaf"   yaf1  142
    run_yaf  yaf_flows_2 "$TESTDATA/flows_2.yaf" yaf2  103
fi

# =============================================================================
# 3. Compression variants
# =============================================================================
echo ""
echo "── compression ──────────────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    for _t in compress_lzo compress_lz4 compress_bz2 compress_zstd; do
        skip "$_t: --enable-readpcap not compiled in"
    done
else
    COMP_PCAP="$TESTDATA/flows_v9_unsamp.pcap"
    COMP_EXPECTED=161

    for codec in lzo lz4 bz2 zstd; do
        cname="compress_$codec"
        cdir="$WORKDIR/$cname"
        mkdir -p "$cdir"
        nfcapd -f "$COMP_PCAP" -w "$cdir" -I comp "-z=$codec" -v 0 >/dev/null 2>&1
        crc=$?
        if [ "$crc" -ne 0 ]; then
            skip "$cname: codec not compiled in (exit $crc)"
        else
            cf=$(ls "$cdir"/nfcapd.* 2>/dev/null | head -1)
            if [ -z "$cf" ]; then
                fail "$cname: no output file"
            else
                cgot=$(count_flows "$cf")
                if [ "${cgot:-0}" -eq "$COMP_EXPECTED" ]; then
                    pass "$cname: $cgot flows"
                else
                    fail "$cname: expected $COMP_EXPECTED flows, got ${cgot:-0}"
                fi
            fi
        fi
    done
fi

# =============================================================================
# 4. File encryption
# =============================================================================
echo ""
echo "── encryption ──────────────────────────────────────────────────────────"

HAS_CRYPTO=0
"$NFCAPD_BIN" -V 2>&1 | grep -qi 'crypto' && HAS_CRYPTO=1

if [ "$HAS_CRYPTO" -eq 0 ]; then
    for _t in crypto_write crypto_read crypto_flowcount crypto_wrongpass; do
        skip "$_t: libsodium not compiled in (--with-libsodium)"
    done
elif [ "$HAS_PCAP" -eq 0 ]; then
    for _t in crypto_write crypto_read crypto_flowcount crypto_wrongpass; do
        skip "$_t: --enable-readpcap not compiled in"
    done
else
    CRYPTO_PCAP="$TESTDATA/flows_v9_unsamp.pcap"
    CRYPTO_EXPECTED=161
    CRYPTO_PASS="passw0rd"
    CRYPTO_DIR="$WORKDIR/crypto"
    mkdir -p "$CRYPTO_DIR"

    # 4a. Write: nfcapd collects from pcap into an encrypted file
    nfcapd -f "$CRYPTO_PCAP" -w "$CRYPTO_DIR" -I crypto -K="$CRYPTO_PASS" \
           -v 0 >/dev/null 2>&1
    crc=$?
    if [ "$crc" -ne 0 ]; then
        fail "crypto_write: nfcapd exited with status $crc"
        for _t in crypto_read crypto_flowcount crypto_wrongpass; do
            skip "$_t: depends on crypto_write"
        done
    else
        CRYPTO_FILE=$(ls "$CRYPTO_DIR"/nfcapd.* 2>/dev/null | head -1)
        if [ -z "$CRYPTO_FILE" ]; then
            fail "crypto_write: no output file created"
            for _t in crypto_read crypto_flowcount crypto_wrongpass; do
                skip "$_t: depends on crypto_write"
            done
        else
            pass "crypto_write: encrypted file created"

            # 4b. Read: nfdump can decrypt and read the file
            if "$NFDUMP_BIN" -G none -r "$CRYPTO_FILE" -K="$CRYPTO_PASS" \
                             -o null >/dev/null 2>&1; then
                pass "crypto_read: decryption OK"
            else
                fail "crypto_read: nfdump could not decrypt file"
            fi

            # 4c. Flow count: decrypted output matches expected count
            got=$(count_flows "$CRYPTO_FILE" "-K=$CRYPTO_PASS")
            if [ "${got:-0}" -eq "$CRYPTO_EXPECTED" ]; then
                pass "crypto_flowcount: $got flows"
            else
                fail "crypto_flowcount: expected $CRYPTO_EXPECTED flows, got ${got:-0}"
            fi

            # 4d. Wrong passphrase must be rejected.
            # nfdump returns NULL from GetNextFile() on bad password rather than
            # EXIT_FAILURE, so we cannot rely on the exit code.  Capture stderr
            # and look for the key-check error message instead.
            wp_err=$("$NFDUMP_BIN" -G none -r "$CRYPTO_FILE" "-K=wrongpass" \
                                   -o null 2>&1)
            if echo "$wp_err" | grep -qi "wrong passphrase\|corrupt.*key\|corrupt.*encr"; then
                pass "crypto_wrongpass: wrong passphrase correctly rejected"
            else
                fail "crypto_wrongpass: expected key-check error on stderr, got: ${wp_err:-<nothing>}"
            fi
        fi
    fi
fi

# =============================================================================
# 5. Extension filtering  (-X flag)
# =============================================================================
echo ""
echo "── extension filtering ──────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    skip "ext_filter: --enable-readpcap not compiled in"
else
    # Extensions 1,2,4,5 = EXgenericFlow, EXipv4Flow, EXinterface, EXflowMisc.
    # Flow count must equal the unfiltered count; only stored fields differ.
    run_pcap  ext_filter  "$TESTDATA/flows_v9_unsamp.pcap"  exttest  161  -X 1,2,4,5
fi

# =============================================================================
# 6. Live network round-trip
# =============================================================================
echo ""
echo "── live network round-trip ──────────────────────────────────────────────"

# Source file: dummy_flows.nf is generated by nfgen4 via runprepare.sh and
# must exist before running these tests ('make check' handles this).
DUMMY_NF="$SCRIPT_DIR/dummy_flows.nf"

if [ ! -x "$NFREPLAY_BIN" ]; then
    skip "live_v9:            nfreplay binary not available"
    skip "live_ipfix:         nfreplay binary not available"
    skip "live_v5:            nfreplay binary not available"
    skip "live_append_rename: nfreplay binary not available"
elif [ ! -f "$DUMMY_NF" ]; then
    skip "live_v9:            $DUMMY_NF missing (run runprepare.sh first)"
    skip "live_ipfix:         $DUMMY_NF missing (run runprepare.sh first)"
    skip "live_v5:            $DUMMY_NF missing (run runprepare.sh first)"
    skip "live_append_rename: $DUMMY_NF missing (run runprepare.sh first)"
else
    # Reference: number of flows in dummy_flows.nf according to its stats block.
    REF_FLOWS=$(count_flows "$DUMMY_NF")

    if [ -z "$REF_FLOWS" ] || [ "$REF_FLOWS" -eq 0 ]; then
        skip "live_v9:            could not read flow count from $DUMMY_NF"
        skip "live_ipfix:         could not read flow count from $DUMMY_NF"
        skip "live_v5:            could not read flow count from $DUMMY_NF"
        skip "live_append_rename: could not read flow count from $DUMMY_NF"
    else
        # Port selection: base on PID, offset from 49152 to avoid conflicts
        # with runtest.sh (which uses 65530) and OS ephemeral range on Linux.
        BASE_PORT=$(( 49152 + $$ % 16000 ))
        PORT_V9=$(( BASE_PORT ))
        PORT_V10=$(( BASE_PORT + 1 ))
        PORT_V5=$(( BASE_PORT + 2 ))
        PORT_AP=$(( BASE_PORT + 3 ))

        # ── 5a. v9 round-trip ────────────────────────────────────────────────
        # nfreplay cannot encode all record types in every netflow version, so
        # the received count may be slightly lower than REF_FLOWS.  Pass if
        # at least half of REF_FLOWS are received (catches total failures while
        # tolerating protocol-encoding drops).
        LIVE_V9="$WORKDIR/live_v9"
        mkdir -p "$LIVE_V9"
        nfcapd -p "$PORT_V9" -4 -w "$LIVE_V9" -D \
               -P "$LIVE_V9/pidfile" -I live_v9 -v 0 >/dev/null 2>&1
        sleep 1
        nfreplay -r "$DUMMY_NF" -v 9 -H 127.0.0.1 -p "$PORT_V9" >/dev/null 2>&1
        sleep 1
        kill -TERM "$(cat "$LIVE_V9/pidfile" 2>/dev/null)" 2>/dev/null || true
        wait_stop "$LIVE_V9/pidfile" 5

        if [ -f "$LIVE_V9/pidfile" ]; then
            fail "live_v9: nfcapd did not terminate within 5 s"
            LIVE_V9_FLOWS=0
        else
            v9f=$(ls "$LIVE_V9"/nfcapd.* 2>/dev/null | head -1)
            if [ -z "$v9f" ]; then
                fail "live_v9: no output file created"
                LIVE_V9_FLOWS=0
            else
                LIVE_V9_FLOWS=$(count_flows "$v9f")
                v9min=$(( REF_FLOWS / 2 ))
                if [ "${LIVE_V9_FLOWS:-0}" -ge "$v9min" ]; then
                    pass "live_v9: ${LIVE_V9_FLOWS} flows (ref=${REF_FLOWS})"
                else
                    fail "live_v9: ${LIVE_V9_FLOWS:-0} flows, expected >= $v9min (ref=${REF_FLOWS})"
                fi
            fi
        fi

        # ── 5a½. IPFIX v10 round-trip ────────────────────────────────────────────
        # IPFIX (RFC 7011) uses a 16-byte message header (version=10, total
        # length in bytes, exportTime, sequence=cumulative data records,
        # observationDomainID) and template set ID 2 instead of 0.  All
        # data-record IE numbers are identical to NetFlow v9, so nfcapd
        # dispatches to Process_IPFIX which handles the same field set.
        # Accept at least half of REF_FLOWS.
        LIVE_V10="$WORKDIR/live_ipfix"
        mkdir -p "$LIVE_V10"
        nfcapd -p "$PORT_V10" -4 -w "$LIVE_V10" -D \
               -P "$LIVE_V10/pidfile" -I live_ipfix -v 0 >/dev/null 2>&1
        sleep 1
        nfreplay -r "$DUMMY_NF" -v 10 -H 127.0.0.1 -p "$PORT_V10" >/dev/null 2>&1
        sleep 1
        kill -TERM "$(cat "$LIVE_V10/pidfile" 2>/dev/null)" 2>/dev/null || true
        wait_stop "$LIVE_V10/pidfile" 5

        if [ -f "$LIVE_V10/pidfile" ]; then
            fail "live_ipfix: nfcapd did not terminate within 5 s"
        else
            v10f=$(ls "$LIVE_V10"/nfcapd.* 2>/dev/null | head -1)
            if [ -z "$v10f" ]; then
                fail "live_ipfix: no output file created"
            else
                v10got=$(count_flows "$v10f")
                v10min=$(( REF_FLOWS / 2 ))
                if [ "${v10got:-0}" -ge "$v10min" ]; then
                    pass "live_ipfix: ${v10got} flows (ref=${REF_FLOWS})"
                else
                    fail "live_ipfix: ${v10got:-0} flows, expected >= $v10min (ref=${REF_FLOWS})"
                fi
            fi
        fi

        # ── 5b. v5 round-trip ────────────────────────────────────────────────
        # v5 carries IPv4 only; IPv6 and other record types are silently
        # dropped by nfreplay.  Accept any count >= 1.
        LIVE_V5="$WORKDIR/live_v5"
        mkdir -p "$LIVE_V5"
        nfcapd -p "$PORT_V5" -4 -w "$LIVE_V5" -D \
               -P "$LIVE_V5/pidfile" -I live_v5 -v 0 >/dev/null 2>&1
        sleep 1
        nfreplay -r "$DUMMY_NF" -v 5 -H 127.0.0.1 -p "$PORT_V5" >/dev/null 2>&1
        sleep 1
        kill -TERM "$(cat "$LIVE_V5/pidfile" 2>/dev/null)" 2>/dev/null || true
        wait_stop "$LIVE_V5/pidfile" 5

        if [ -f "$LIVE_V5/pidfile" ]; then
            fail "live_v5: nfcapd did not terminate within 5 s"
        else
            v5f=$(ls "$LIVE_V5"/nfcapd.* 2>/dev/null | head -1)
            if [ -z "$v5f" ]; then
                fail "live_v5: no output file created"
            else
                v5got=$(count_flows "$v5f")
                if [ "${v5got:-0}" -ge 1 ]; then
                    pass "live_v5: ${v5got} flows (ref=${REF_FLOWS})"
                else
                    fail "live_v5: 0 flows received"
                fi
            fi
        fi

        # ── 5c. AppendRename (two consecutive collection cycles) ─────────────
        #
        # With -t 3600 both cycles align to the same rotation slot.  The second
        # nfcapd instance must AppendRename the in-progress file left by the
        # first instance.  Total flows across all output files must equal
        # 2 × LIVE_V9_FLOWS (each cycle replays the same source).
        LIVE_AP="$WORKDIR/live_append"
        mkdir -p "$LIVE_AP"

        # Cycle 1
        nfcapd -p "$PORT_AP" -4 -w "$LIVE_AP" -D \
               -P "$LIVE_AP/pidfile" -I append -t 3600 -v 0 >/dev/null 2>&1
        sleep 1
        nfreplay -r "$DUMMY_NF" -v 9 -H 127.0.0.1 -p "$PORT_AP" >/dev/null 2>&1
        sleep 1
        kill -TERM "$(cat "$LIVE_AP/pidfile" 2>/dev/null)" 2>/dev/null || true
        wait_stop "$LIVE_AP/pidfile" 5

        # Cycle 2
        nfcapd -p "$PORT_AP" -4 -w "$LIVE_AP" -D \
               -P "$LIVE_AP/pidfile" -I append -t 3600 -v 0 >/dev/null 2>&1
        sleep 1
        nfreplay -r "$DUMMY_NF" -v 9 -H 127.0.0.1 -p "$PORT_AP" >/dev/null 2>&1
        sleep 1
        kill -TERM "$(cat "$LIVE_AP/pidfile" 2>/dev/null)" 2>/dev/null || true
        wait_stop "$LIVE_AP/pidfile" 5

        if [ -f "$LIVE_AP/pidfile" ]; then
            fail "live_append_rename: nfcapd did not terminate on second cycle"
        else
            ap_total=0
            for apf in "$LIVE_AP"/nfcapd.*; do
                [ -f "$apf" ] || continue
                apc=$(count_flows "$apf")
                ap_total=$(( ap_total + ${apc:-0} ))
            done
            ap_expected=$(( LIVE_V9_FLOWS * 2 ))
            if [ "$ap_expected" -gt 0 ] && [ "$ap_total" -eq "$ap_expected" ]; then
                pass "live_append_rename: $ap_total flows across 2 cycles"
            elif [ "$ap_expected" -eq 0 ]; then
                skip "live_append_rename: v9 baseline was 0, cannot validate total"
            else
                fail "live_append_rename: expected $ap_expected flows, got $ap_total"
            fi
        fi
    fi
fi   # nfreplay / dummy_flows.nf available

# =============================================================================
# 7. Memory / allocator guard checks (pcap mode)
# =============================================================================
echo ""
echo "── memory guard checks ──────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    for _t in memck_flows_v5_unsamp memck_flows_v9_unsamp memck_flows_ipfix_unsamp \
              memck_nsel memck_CGNAT-ifvrf; do
        skip "$_t: --enable-readpcap not compiled in"
    done
else
    # Activate platform-specific allocator diagnostics.
    export MALLOC_OPTIONS=CFGJS         # OpenBSD
    export MallocGuardEdges=1           # macOS
    export MallocScribble=1
    export MallocErrorAbort=1
    export MallocCorruptionAbort=1

    for pcap in \
        "$TESTDATA/flows_v5_unsamp.pcap" \
        "$TESTDATA/flows_v9_unsamp.pcap" \
        "$TESTDATA/flows_ipfix_unsamp.pcap" \
        "$TESTDATA/nsel.pcap" \
        "$TESTDATA/CGNAT-ifvrf.pcap"; do

        mname="memck_$(basename "$pcap" .pcap)"
        md="$WORKDIR/$mname"
        mkdir -p "$md"
        if nfcapd -f "$pcap" -w "$md" -I memck -v 0 >/dev/null 2>&1; then
            pass "$mname"
        else
            fail "$mname: nfcapd crashed or returned non-zero under memory guards"
        fi
    done

    unset MALLOC_OPTIONS MallocGuardEdges MallocScribble MallocErrorAbort \
          MallocCorruptionAbort
fi

# =============================================================================
# 8. Post-decode record filter (-F)
# =============================================================================
echo ""
echo "── post-decode record filter (-F) ───────────────────────────────────────"

FILTER_TESTS="filter_keep_all filter_drop_all filter_partial filter_reject filter_reject_ident filter_reject_count filter_as_plain filter_stat_block"

if [ "$HAS_PCAP" -eq 0 ]; then
    for _t in $FILTER_TESTS; do
        skip "$_t: --enable-readpcap not compiled in"
    done
else
    FILTER_PCAP="$TESTDATA/flows_v9_unsamp.pcap"

    # Unfiltered baseline: actual record count with no -F at all.
    FBASE_DIR="$WORKDIR/filter_baseline"
    mkdir -p "$FBASE_DIR"
    nfcapd -f "$FILTER_PCAP" -w "$FBASE_DIR" -I fbase -v 0 >/dev/null 2>&1
    FBASE_FILE=$(ls "$FBASE_DIR"/nfcapd.* 2>/dev/null | head -1)

    if [ -z "$FBASE_FILE" ]; then
        for _t in $FILTER_TESTS; do
            skip "$_t: could not create unfiltered baseline"
        done
    else
        BASE_COUNT=$(count_records "$FBASE_FILE")

        # 8a. A filter matching every record must retain the full baseline count.
        run_pcap_filter filter_keep_all "$FILTER_PCAP" fkeep \
            "not bytes > 999999999" "${BASE_COUNT:-0}"

        # 8b. A filter matching no record must leave 0 records stored.
        run_pcap_filter filter_drop_all "$FILTER_PCAP" fdrop \
            "bytes > 999999999" 0

        # 8c. Parity check: a partial filter's collection-time result must
        # exactly match the same expression applied at nfdump read-time
        # against the unfiltered baseline — the collector's post-filter and
        # nfdump's own filter both compile through the same engine
        # (libnffilter vs. libnfdump share filter.c/grammar.y), so they must
        # agree record-for-record.
        PARTIAL_EXPR="proto tcp"
        GROUND_TRUTH=$(count_records "$FBASE_FILE" "$PARTIAL_EXPR")
        if [ -z "$GROUND_TRUTH" ]; then
            skip "filter_partial: could not compute ground truth"
        else
            run_pcap_filter filter_partial "$FILTER_PCAP" fpartial \
                "$PARTIAL_EXPR" "$GROUND_TRUTH"
        fi

        # 8d. A filter needing a resource outside the plain V4 record
        # (MaxMind geo lookup here) must be rejected at compile time: nfcapd
        # exits non-zero immediately and never creates an output file.
        FREJECT_DIR="$WORKDIR/filter_reject"
        mkdir -p "$FREJECT_DIR"
        nfcapd -f "$FILTER_PCAP" -w "$FREJECT_DIR" -I freject \
               -F "src geo US" -v 0 >/dev/null 2>&1
        frc=$?
        frej_file=$(ls "$FREJECT_DIR"/nfcapd.* 2>/dev/null | head -1)
        if [ "$frc" -ne 0 ] && [ -z "$frej_file" ]; then
            pass "filter_reject: 'src geo US' correctly rejected at compile time"
        else
            fail "filter_reject: expected non-zero exit and no output file (exit=$frc, file=${frej_file:-none})"
        fi

        # 8e. ident is a source-level nfdump query parameter, not a V4
        # record field. The collector profile must reject it rather than
        # silently comparing every record with the engine's default ident.
        FIDENT_DIR="$WORKDIR/filter_reject_ident"
        mkdir -p "$FIDENT_DIR"
        nfcapd -f "$FILTER_PCAP" -w "$FIDENT_DIR" -I frejectident \
               -F "ident frejectident" -v 0 >/dev/null 2>&1
        firc=$?
        fident_file=$(ls "$FIDENT_DIR"/nfcapd.* 2>/dev/null | head -1)
        if [ "$firc" -ne 0 ] && [ -z "$fident_file" ]; then
            pass "filter_reject_ident: source-level ident correctly rejected"
        else
            fail "filter_reject_ident: expected non-zero exit and no output file (exit=$firc, file=${fident_file:-none})"
        fi

        # 8f. count is the query engine's ordinal record counter, not a
        # record field. In a block pipeline it would reset at every block, so
        # the collector profile must reject it.
        FCOUNT_DIR="$WORKDIR/filter_reject_count"
        mkdir -p "$FCOUNT_DIR"
        nfcapd -f "$FILTER_PCAP" -w "$FCOUNT_DIR" -I frejectcount \
               -F "count > 0" -v 0 >/dev/null 2>&1
        fcrc=$?
        fcount_file=$(ls "$FCOUNT_DIR"/nfcapd.* 2>/dev/null | head -1)
        if [ "$fcrc" -ne 0 ] && [ -z "$fcount_file" ]; then
            pass "filter_reject_count: query ordinal correctly rejected"
        else
            fail "filter_reject_count: expected non-zero exit and no output file (exit=$fcrc, file=${fcount_file:-none})"
        fi

        # 8g. "as <num>" must NOT be rejected: mmASLookup_function() never
        # enriches when the exporter's own AS field is 0 (see filter.c), so
        # this stays a plain field compare and must compile and run. These
        # fixtures carry no AS info, so 0 matching records is the expected,
        # correct outcome — what this guards against is nfcapd rejecting the
        # filter outright (run_pcap_filter reports that as a distinct
        # "exited with status" failure, not a count mismatch).
        run_pcap_filter filter_as_plain "$FILTER_PCAP" fas "as 12345" 0

        # 8h. Metadata regression: the filter stage derives both cycle stats
        # and cumulative exporter flow counts from retained records. -I, -E,
        # and an actual record read must therefore agree on a filtered file.
        FSTAT_DIR="$WORKDIR/filter_stat"
        mkdir -p "$FSTAT_DIR"
        nfcapd -f "$FILTER_PCAP" -w "$FSTAT_DIR" -I fstat -F "proto tcp" -v 0 >/dev/null 2>&1
        fstat_file=$(ls "$FSTAT_DIR"/nfcapd.* 2>/dev/null | head -1)
        if [ -z "$fstat_file" ]; then
            fail "filter_stat_block: no output file created"
        else
            fstat_i=$(count_flows "$fstat_file")
            fstat_r=$(count_records "$fstat_file")
            fstat_e=$(count_exporter_flows "$fstat_file")
            if [ "${fstat_i:-0}" -eq "${fstat_r:-0}" ] && [ "${fstat_e:-0}" -eq "${fstat_r:-0}" ] && [ "${fstat_r:-0}" -eq "${GROUND_TRUTH:-0}" ]; then
                pass "filter_stat_block: -I/-E ($fstat_i/$fstat_e) match actual records ($fstat_r)"
            else
                fail "filter_stat_block: -I/-E report $fstat_i/$fstat_e, actual records $fstat_r (expected all = ${GROUND_TRUTH:-0})"
            fi
        fi
    fi
fi

summary
