#!/bin/sh
#  This file is part of the nfdump project.
#
#  Copyright (c) 2026, Peter Haag
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#   * Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#   * Neither the name of Peter Haag nor the names of its contributors may be
#     used to endorse or promote products derived from this software without
#     specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
# Native nfdump protocol live round-trip regression tests.
#
# Tests:
#   1. v250_plain           — plain nfdump native protocol (version 250)
#   2. v251_encrypted       — XChaCha20-Poly1305 encrypted protocol (version 251)
#   3. v251_wrong_passphrase — wrong passphrase: all packets must be rejected
#
# Protocol version 250:
#   nfreplay -v 250  forwards flow records verbatim as raw nfdump V4 records
#   inside an nfd_header UDP frame.  nfcapd receives and stores them without
#   any special configuration.
#
# Protocol version 251:
#   nfreplay -v 250 -k=<pass>  assembles a v250 inner packet, then encrypts it
#   with XChaCha20-Poly1305 (per-packet random 192-bit nonce, 16-byte Poly1305
#   MAC) and sends the result as a v251 wire packet.
#   nfcapd -k=<pass>  derives the same session key via Argon2id and decrypts
#   incoming v251 packets before processing them.
#   Note: to also encrypt the output .nf files supply -K=<pass> to nfcapd;
#   nfdump -K is then required to read them back.
#
# Prerequisites:
#   • nfcapd and nfreplay binaries
#   • dummy_flows.nf  generated by test_prepare.sh (nfgen4)
#   • For tests 2 and 3: both binaries compiled with --with-libsodium
#     (detected via 'CRYPTO' in nfcapd -V / nfreplay -V output)

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/testsetup.sh"

# ── helpers ───────────────────────────────────────────────────────────────────

# count_flows FILE [EXTRA_NFDUMP_ARG]
# Uses nfdump -I (statistics block) — immune to debug output.
# EXTRA_NFDUMP_ARG is typically "-K=<passphrase>" for encrypted files.
count_flows() {
    local extra=""
    [ -n "${2-}" ] && extra="$2"
    "$NFDUMP_BIN" -G none -I -r "$1" ${extra:+"$extra"} 2>/dev/null \
        | awk '/^Flows:/{s += $2} END{print s+0}'
}

# wait_stop PIDFILE [SECONDS]
wait_stop() {
    local pf="$1" max="${2:-5}" i=0
    while [ -f "$pf" ] && [ "$i" -lt "$max" ]; do
        sleep 1; i=$((i+1))
    done
}

# =============================================================================
# Prerequisite checks
# =============================================================================
echo ""
echo "── prerequisites ────────────────────────────────────────────────────────"

PREREQ_OK=1
DUMMY_NF="$SCRIPT_DIR/dummy_flows.nf"

if [ ! -x "$NFCAPD_BIN" ]; then
    echo "  ERROR: nfcapd not found: $NFCAPD_BIN"; PREREQ_OK=0
fi
if [ ! -x "$NFREPLAY_BIN" ]; then
    echo "  ERROR: nfreplay not found: $NFREPLAY_BIN"; PREREQ_OK=0
fi
if [ ! -f "$DUMMY_NF" ]; then
    echo "  ERROR: $DUMMY_NF missing — run test_prepare.sh first"; PREREQ_OK=0
fi

if [ "$PREREQ_OK" -eq 0 ]; then
    echo "  Skip test: missing prerequisites."
    exit 0
fi

# Detect libsodium: both nfcapd and nfreplay must report CRYPTO in their
# version string for the encrypted tests to be meaningful.
HAS_SODIUM=0
if "$NFCAPD_BIN"  -V 2>&1 | grep -q 'CRYPTO' && \
   "$NFREPLAY_BIN" -V 2>&1 | grep -q 'CRYPTO'; then
    HAS_SODIUM=1
fi

echo "  nfcapd:      $NFCAPD_BIN"
echo "  nfreplay:    $NFREPLAY_BIN"
echo "  dummy_flows: $DUMMY_NF"
if [ "$HAS_SODIUM" -eq 1 ]; then
    echo "  libsodium:   yes (v251 tests enabled)"
else
    echo "  libsodium:   no  (v251 tests will be skipped)"
    echo "               Rebuild with: ./configure --with-libsodium"
fi

REF_FLOWS=$(count_flows "$DUMMY_NF")
if [ -z "$REF_FLOWS" ] || [ "$REF_FLOWS" -eq 0 ]; then
    echo "  ERROR: could not read flow count from $DUMMY_NF"
    exit 1
fi
echo "  ref flows:   $REF_FLOWS"

# Minimum acceptable received count (half of source, to tolerate protocol drops).
MIN_FLOWS=$(( REF_FLOWS / 2 ))

# Port selection: PID-based offset in the 49152–65151 range, step by 3 to
# leave room for the three tests without collision.
BASE_PORT=$(( 49152 + ( $$ * 3 ) % 16000 ))
PORT_V250=$(( BASE_PORT ))
PORT_V251=$(( BASE_PORT + 1 ))
PORT_WRNG=$(( BASE_PORT + 2 ))

PASSPHRASE="nfdump-test-v251-secret"

# =============================================================================
# 1. v250 plain round-trip
# =============================================================================
echo ""
echo "── v250 plain nfdump protocol ───────────────────────────────────────────"

LIVE_V250="$WORKDIR/live_v250"
mkdir -p "$LIVE_V250"

nfcapd -p "$PORT_V250" -4 -w "$LIVE_V250" -D \
       -P "$LIVE_V250/pidfile" -I live_v250 -v 0 >/dev/null 2>&1
sleep 1
nfreplay -r "$DUMMY_NF" -v 250 -H 127.0.0.1 -p "$PORT_V250" >/dev/null 2>&1
sleep 1
kill -TERM "$(cat "$LIVE_V250/pidfile" 2>/dev/null)" 2>/dev/null || true
wait_stop "$LIVE_V250/pidfile" 5

if [ -f "$LIVE_V250/pidfile" ]; then
    fail "v250_plain: nfcapd did not terminate within 5 s"
else
    v250f=$(ls "$LIVE_V250"/nfcapd.* 2>/dev/null | head -1)
    if [ -z "$v250f" ]; then
        fail "v250_plain: no output file created"
    else
        v250got=$(count_flows "$v250f")
        if [ "${v250got:-0}" -ge "$MIN_FLOWS" ]; then
            pass "v250_plain: ${v250got} flows (ref=${REF_FLOWS})"
        else
            fail "v250_plain: ${v250got:-0} flows, expected >= $MIN_FLOWS (ref=${REF_FLOWS})"
        fi
    fi
fi

# =============================================================================
# 2. v251 encrypted round-trip
# =============================================================================
echo ""
echo "── v251 encrypted nfdump protocol ───────────────────────────────────────"

if [ "$HAS_SODIUM" -eq 0 ]; then
    skip "v251_encrypted: libsodium not compiled in"
else
    LIVE_V251="$WORKDIR/live_v251"
    mkdir -p "$LIVE_V251"

    # nfcapd -k: derive UDP session key for incoming v251 decryption.
    #            Output .nf files are stored unencrypted (no -K).
    nfcapd -p "$PORT_V251" -4 -w "$LIVE_V251" -D \
           -P "$LIVE_V251/pidfile" -I live_v251 \
           "-k=$PASSPHRASE" -v 0 >/dev/null 2>&1
    sleep 1
    nfreplay -r "$DUMMY_NF" -v 250 -H 127.0.0.1 -p "$PORT_V251" \
             "-k=$PASSPHRASE" >/dev/null 2>&1
    sleep 1
    kill -TERM "$(cat "$LIVE_V251/pidfile" 2>/dev/null)" 2>/dev/null || true
    wait_stop "$LIVE_V251/pidfile" 5

    if [ -f "$LIVE_V251/pidfile" ]; then
        fail "v251_encrypted: nfcapd did not terminate within 5 s"
    else
        v251f=$(ls "$LIVE_V251"/nfcapd.* 2>/dev/null | head -1)
        if [ -z "$v251f" ]; then
            fail "v251_encrypted: no output file created"
        else
            # Output files are unencrypted (no -K on nfcapd); count without extra arg.
            v251got=$(count_flows "$v251f")
            if [ "${v251got:-0}" -ge "$MIN_FLOWS" ]; then
                pass "v251_encrypted: ${v251got} flows (ref=${REF_FLOWS})"
            else
                fail "v251_encrypted: ${v251got:-0} flows, expected >= $MIN_FLOWS (ref=${REF_FLOWS})"
            fi
        fi
    fi
fi

# =============================================================================
# 3. v251 wrong passphrase — packets must be rejected
# =============================================================================
echo ""
echo "── v251 wrong passphrase rejection ──────────────────────────────────────"

if [ "$HAS_SODIUM" -eq 0 ]; then
    skip "v251_wrong_passphrase: libsodium not compiled in"
else
    LIVE_WRNG="$WORKDIR/live_v251_wrong"
    mkdir -p "$LIVE_WRNG"

    # Receiver uses the correct passphrase; sender uses a different one.
    # The Poly1305 MAC verification on the receiver must fail for every packet,
    # resulting in zero flows stored.
    nfcapd -p "$PORT_WRNG" -4 -w "$LIVE_WRNG" -D \
           -P "$LIVE_WRNG/pidfile" -I live_v251_wrong \
           "-k=$PASSPHRASE" -v 0 >/dev/null 2>&1
    sleep 1
    nfreplay -r "$DUMMY_NF" -v 250 -H 127.0.0.1 -p "$PORT_WRNG" \
             "-k=wrong-passphrase-xyz" >/dev/null 2>&1
    sleep 1
    kill -TERM "$(cat "$LIVE_WRNG/pidfile" 2>/dev/null)" 2>/dev/null || true
    wait_stop "$LIVE_WRNG/pidfile" 5

    if [ -f "$LIVE_WRNG/pidfile" ]; then
        fail "v251_wrong_passphrase: nfcapd did not terminate within 5 s"
    else
        wrnf=$(ls "$LIVE_WRNG"/nfcapd.* 2>/dev/null | head -1)
        if [ -z "$wrnf" ]; then
            # nfcapd may not create a file if it received no valid packets.
            pass "v251_wrong_passphrase: no output file — all packets rejected"
        else
            wrngot=$(count_flows "$wrnf")
            if [ "${wrngot:-0}" -eq 0 ]; then
                pass "v251_wrong_passphrase: 0 flows stored — all packets rejected"
            else
                fail "v251_wrong_passphrase: ${wrngot} flows stored — wrong-passphrase packets should have been rejected"
            fi
        fi
    fi
fi

summary
