#!/bin/sh
#  This file is part of the nfdump project.
#
#  Copyright (c) 2023, Peter Haag
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#
#   * Redistributions of source code must retain the above copyright notice,
#     this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright notice,
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#   * Neither the name of Peter Haag nor the names of its contributors may be
#     used to endorse or promote products derived from this software without
#     specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
# nfcapd regression test suite.
# Tests: pcap file mode (v5/v9/IPFIX/NSEL/CGNAT/timeflows),
#        YAF file mode, compression variants, extension filtering,
#        live network round-trip (v9 and v5), AppendRename, memory guards.
#
# Portability: POSIX sh; tested on Linux, *BSD, macOS.
#   'local' is used in helpers — supported by all modern /bin/sh implementations
#   (bash, dash, ksh88+, zsh, busybox ash) even though not in POSIX:2017.
#
# pcap/YAF tests require nfcapd compiled with --enable-readpcap.
# Live round-trip tests require nfreplay and dummy_flows.nf (generated by
# runprepare.sh / nfgen4 during 'make check').

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/testsetup.sh"

# ── helpers ───────────────────────────────────────────────────────────────────

# count_flows FILE
# Reads the statistics block written by nfcapd (-I flag).  This is immune to
# the verbose debug lines that nfdump may print on stdout in devel builds.
count_flows() {
    "$NFDUMP_BIN" -G none -I -r "$1" 2>/dev/null \
        | awk '/^Flows:/{s += $2} END{print s+0}'
}

# wait_stop PIDFILE [SECONDS]
wait_stop() {
    local pf="$1" max="${2:-5}" i=0
    while [ -f "$pf" ] && [ "$i" -lt "$max" ]; do
        sleep 1; i=$((i+1))
    done
}

# ── pcap file-mode test ───────────────────────────────────────────────────────
# run_pcap NAME PCAPFILE IDENT EXPECTED [extra nfcapd args…]
run_pcap() {
    local name="$1" pcap="$2" ident="$3" expected="$4"
    shift 4
    local d="$WORKDIR/$name"
    mkdir -p "$d"
    nfcapd -f "$pcap" -w "$d" -I "$ident" "$@" -v 0 >/dev/null 2>&1
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        fail "$name: nfcapd exited with status $rc"
        return
    fi
    local f
    f=$(ls "$d"/nfcapd.* 2>/dev/null | head -1)
    if [ -z "$f" ]; then
        fail "$name: no output file created"
        return
    fi
    local got
    got=$(count_flows "$f")
    if [ "${got:-0}" -eq "$expected" ]; then
        pass "$name: $got flows"
    else
        fail "$name: expected $expected flows, got ${got:-0}"
    fi
}

# ── YAF file-mode test ────────────────────────────────────────────────────────
# run_yaf NAME YAFFILE IDENT EXPECTED
run_yaf() {
    local name="$1" yaf="$2" ident="$3" expected="$4"
    local d="$WORKDIR/$name"
    mkdir -p "$d"
    nfcapd -Y "$yaf" -w "$d" -I "$ident" -v 0 >/dev/null 2>&1
    local rc=$?
    if [ "$rc" -ne 0 ]; then
        fail "$name: nfcapd exited with status $rc"
        return
    fi
    local f
    f=$(ls "$d"/nfcapd.* 2>/dev/null | head -1)
    if [ -z "$f" ]; then
        fail "$name: no output file created"
        return
    fi
    local got
    got=$(count_flows "$f")
    if [ "${got:-0}" -eq "$expected" ]; then
        pass "$name: $got flows"
    else
        fail "$name: expected $expected flows, got ${got:-0}"
    fi
}

# =============================================================================
# Prerequisite checks
# =============================================================================
echo ""
echo "── prerequisites ────────────────────────────────────────────────────────"
PREREQ_OK=1

if [ ! -x "$NFCAPD_BIN" ]; then
    echo "  ERROR: nfcapd not found: $NFCAPD_BIN"; PREREQ_OK=0; fi
if [ ! -x "$NFDUMP_BIN" ]; then
    echo "  ERROR: nfdump not found: $NFDUMP_BIN";  PREREQ_OK=0; fi
if [ -z "$TESTDATA" ] || [ ! -d "$TESTDATA" ]; then
    echo "  ERROR: test data directory not found (expected test/nfcapd/)"; PREREQ_OK=0; fi

if [ "$PREREQ_OK" -eq 0 ]; then
    echo "  Aborting: missing prerequisites."
    exit 1
fi

# Detect whether nfcapd was compiled with --enable-readpcap.
# Without it, the -f (pcap) and -Y (yaf) flags are absent from the help text.
HAS_PCAP=0
"$NFCAPD_BIN" -h 2>&1 | grep -q '\-f pcapfile' && HAS_PCAP=1

echo "  nfcapd:   $NFCAPD_BIN"
echo "  nfdump:   $NFDUMP_BIN"
echo "  testdata: $TESTDATA"
if [ "$HAS_PCAP" -eq 1 ]; then
    echo "  pcap/YAF: yes"
else
    echo "  pcap/YAF: no  (pcap/YAF/compression/extension/memck sections skipped)"
    echo "            Rebuild with: ./configure --enable-readpcap"
fi

# =============================================================================
# 1. pcap file mode
# =============================================================================
echo ""
echo "── pcap file mode ───────────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    for _t in pcap_v5_unsamp pcap_v5_samp pcap_v9_unsamp pcap_v9_samp \
              pcap_ipfix_unsamp pcap_ipfix_samp pcap_nsel pcap_cgnat pcap_timeflows; do
        skip "$_t: --enable-readpcap not compiled in"
    done
else
    # Expected counts measured with 'nfdump -I -r <file>' (statistics block).
    run_pcap  pcap_v5_unsamp     "$TESTDATA/flows_v5_unsamp.pcap"    v5_unsamp    159
    run_pcap  pcap_v5_samp       "$TESTDATA/flows_v5_samp.pcap"      v5_samp       34
    run_pcap  pcap_v9_unsamp     "$TESTDATA/flows_v9_unsamp.pcap"    v9_unsamp    161
    run_pcap  pcap_v9_samp       "$TESTDATA/flows_v9_samp.pcap"      v9_samp       35
    run_pcap  pcap_ipfix_unsamp  "$TESTDATA/flows_ipfix_unsamp.pcap" ipfix_unsamp 161
    run_pcap  pcap_ipfix_samp    "$TESTDATA/flows_ipfix_samp.pcap"   ipfix_samp    35
    run_pcap  pcap_nsel          "$TESTDATA/nsel.pcap"               nsel         733447
    run_pcap  pcap_cgnat         "$TESTDATA/CGNAT-ifvrf.pcap"        cgnat        15136
    run_pcap  pcap_timeflows     "$TESTDATA/timeflows.pcap"          timeflows        6
fi

# =============================================================================
# 2. YAF file mode
# =============================================================================
echo ""
echo "── YAF file mode ────────────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    skip "yaf_flows:   --enable-readpcap not compiled in"
    skip "yaf_flows_2: --enable-readpcap not compiled in"
else
    run_yaf  yaf_flows   "$TESTDATA/flows.yaf"   yaf1  142
    run_yaf  yaf_flows_2 "$TESTDATA/flows_2.yaf" yaf2  103
fi

# =============================================================================
# 3. Compression variants
# =============================================================================
echo ""
echo "── compression ──────────────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    for _t in compress_lzo compress_lz4 compress_bz2 compress_zstd; do
        skip "$_t: --enable-readpcap not compiled in"
    done
else
    COMP_PCAP="$TESTDATA/flows_v9_unsamp.pcap"
    COMP_EXPECTED=161

    for codec in lzo lz4 bz2 zstd; do
        cname="compress_$codec"
        cdir="$WORKDIR/$cname"
        mkdir -p "$cdir"
        nfcapd -f "$COMP_PCAP" -w "$cdir" -I comp "-z=$codec" -v 0 >/dev/null 2>&1
        crc=$?
        if [ "$crc" -ne 0 ]; then
            skip "$cname: codec not compiled in (exit $crc)"
        else
            cf=$(ls "$cdir"/nfcapd.* 2>/dev/null | head -1)
            if [ -z "$cf" ]; then
                fail "$cname: no output file"
            else
                cgot=$(count_flows "$cf")
                if [ "${cgot:-0}" -eq "$COMP_EXPECTED" ]; then
                    pass "$cname: $cgot flows"
                else
                    fail "$cname: expected $COMP_EXPECTED flows, got ${cgot:-0}"
                fi
            fi
        fi
    done
fi

# =============================================================================
# 4. File encryption
# =============================================================================
echo ""
echo "── encryption ──────────────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    for _t in compress_lzo compress_lz4 compress_bz2 compress_zstd; do
        skip "$_t: --enable-readpcap not compiled in"
    done
else
    COMP_PCAP="$TESTDATA/flows_v9_unsamp.pcap"
    COMP_EXPECTED=161

    for codec in lzo lz4 bz2 zstd; do
        cname="compress_$codec"
        cdir="$WORKDIR/$cname"
        mkdir -p "$cdir"
        nfcapd -f "$COMP_PCAP" -w "$cdir" -I comp "-z=$codec" -v 0 >/dev/null 2>&1
        crc=$?
        if [ "$crc" -ne 0 ]; then
            skip "$cname: codec not compiled in (exit $crc)"
        else
            cf=$(ls "$cdir"/nfcapd.* 2>/dev/null | head -1)
            if [ -z "$cf" ]; then
                fail "$cname: no output file"
            else
                cgot=$(count_flows "$cf")
                if [ "${cgot:-0}" -eq "$COMP_EXPECTED" ]; then
                    pass "$cname: $cgot flows"
                else
                    fail "$cname: expected $COMP_EXPECTED flows, got ${cgot:-0}"
                fi
            fi
        fi
    done
fi

# =============================================================================
# 5. Extension filtering  (-X flag)
# =============================================================================
echo ""
echo "── extension filtering ──────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    skip "ext_filter: --enable-readpcap not compiled in"
else
    # Extensions 1,2,4,5 = EXgenericFlow, EXipv4Flow, EXinterface, EXflowMisc.
    # Flow count must equal the unfiltered count; only stored fields differ.
    run_pcap  ext_filter  "$TESTDATA/flows_v9_unsamp.pcap"  exttest  161  -X 1,2,4,5
fi

# =============================================================================
# 6. Live network round-trip
# =============================================================================
echo ""
echo "── live network round-trip ──────────────────────────────────────────────"

# Source file: dummy_flows.nf is generated by nfgen4 via runprepare.sh and
# must exist before running these tests ('make check' handles this).
DUMMY_NF="$SCRIPT_DIR/dummy_flows.nf"

if [ ! -x "$NFREPLAY_BIN" ]; then
    skip "live_v9:            nfreplay binary not available"
    skip "live_v5:            nfreplay binary not available"
    skip "live_append_rename: nfreplay binary not available"
elif [ ! -f "$DUMMY_NF" ]; then
    skip "live_v9:            $DUMMY_NF missing (run runprepare.sh first)"
    skip "live_v5:            $DUMMY_NF missing (run runprepare.sh first)"
    skip "live_append_rename: $DUMMY_NF missing (run runprepare.sh first)"
else
    # Reference: number of flows in dummy_flows.nf according to its stats block.
    REF_FLOWS=$(count_flows "$DUMMY_NF")

    if [ -z "$REF_FLOWS" ] || [ "$REF_FLOWS" -eq 0 ]; then
        skip "live_v9:            could not read flow count from $DUMMY_NF"
        skip "live_v5:            could not read flow count from $DUMMY_NF"
        skip "live_append_rename: could not read flow count from $DUMMY_NF"
    else
        # Port selection: base on PID, offset from 49152 to avoid conflicts
        # with runtest.sh (which uses 65530) and OS ephemeral range on Linux.
        BASE_PORT=$(( 49152 + $$ % 16000 ))
        PORT_V9=$(( BASE_PORT ))
        PORT_V5=$(( BASE_PORT + 1 ))
        PORT_AP=$(( BASE_PORT + 2 ))

        # ── 5a. v9 round-trip ────────────────────────────────────────────────
        # nfreplay cannot encode all record types in every netflow version, so
        # the received count may be slightly lower than REF_FLOWS.  Pass if
        # at least half of REF_FLOWS are received (catches total failures while
        # tolerating protocol-encoding drops).
        LIVE_V9="$WORKDIR/live_v9"
        mkdir -p "$LIVE_V9"
        nfcapd -p "$PORT_V9" -4 -w "$LIVE_V9" -D \
               -P "$LIVE_V9/pidfile" -I live_v9 -v 0 >/dev/null 2>&1
        sleep 1
        nfreplay -r "$DUMMY_NF" -v 9 -H 127.0.0.1 -p "$PORT_V9" >/dev/null 2>&1
        sleep 1
        kill -TERM "$(cat "$LIVE_V9/pidfile" 2>/dev/null)" 2>/dev/null || true
        wait_stop "$LIVE_V9/pidfile" 5

        if [ -f "$LIVE_V9/pidfile" ]; then
            fail "live_v9: nfcapd did not terminate within 5 s"
            LIVE_V9_FLOWS=0
        else
            v9f=$(ls "$LIVE_V9"/nfcapd.* 2>/dev/null | head -1)
            if [ -z "$v9f" ]; then
                fail "live_v9: no output file created"
                LIVE_V9_FLOWS=0
            else
                LIVE_V9_FLOWS=$(count_flows "$v9f")
                v9min=$(( REF_FLOWS / 2 ))
                if [ "${LIVE_V9_FLOWS:-0}" -ge "$v9min" ]; then
                    pass "live_v9: ${LIVE_V9_FLOWS} flows (ref=${REF_FLOWS})"
                else
                    fail "live_v9: ${LIVE_V9_FLOWS:-0} flows, expected >= $v9min (ref=${REF_FLOWS})"
                fi
            fi
        fi

        # ── 5b. v5 round-trip ────────────────────────────────────────────────
        # v5 carries IPv4 only; IPv6 and other record types are silently
        # dropped by nfreplay.  Accept any count >= 1.
        LIVE_V5="$WORKDIR/live_v5"
        mkdir -p "$LIVE_V5"
        nfcapd -p "$PORT_V5" -4 -w "$LIVE_V5" -D \
               -P "$LIVE_V5/pidfile" -I live_v5 -v 0 >/dev/null 2>&1
        sleep 1
        nfreplay -r "$DUMMY_NF" -v 5 -H 127.0.0.1 -p "$PORT_V5" >/dev/null 2>&1
        sleep 1
        kill -TERM "$(cat "$LIVE_V5/pidfile" 2>/dev/null)" 2>/dev/null || true
        wait_stop "$LIVE_V5/pidfile" 5

        if [ -f "$LIVE_V5/pidfile" ]; then
            fail "live_v5: nfcapd did not terminate within 5 s"
        else
            v5f=$(ls "$LIVE_V5"/nfcapd.* 2>/dev/null | head -1)
            if [ -z "$v5f" ]; then
                fail "live_v5: no output file created"
            else
                v5got=$(count_flows "$v5f")
                if [ "${v5got:-0}" -ge 1 ]; then
                    pass "live_v5: ${v5got} flows (ref=${REF_FLOWS})"
                else
                    fail "live_v5: 0 flows received"
                fi
            fi
        fi

        # ── 5c. AppendRename (two consecutive collection cycles) ─────────────
        #
        # With -t 3600 both cycles align to the same rotation slot.  The second
        # nfcapd instance must AppendRename the in-progress file left by the
        # first instance.  Total flows across all output files must equal
        # 2 × LIVE_V9_FLOWS (each cycle replays the same source).
        LIVE_AP="$WORKDIR/live_append"
        mkdir -p "$LIVE_AP"

        # Cycle 1
        nfcapd -p "$PORT_AP" -4 -w "$LIVE_AP" -D \
               -P "$LIVE_AP/pidfile" -I append -t 3600 -v 0 >/dev/null 2>&1
        sleep 1
        nfreplay -r "$DUMMY_NF" -v 9 -H 127.0.0.1 -p "$PORT_AP" >/dev/null 2>&1
        sleep 1
        kill -TERM "$(cat "$LIVE_AP/pidfile" 2>/dev/null)" 2>/dev/null || true
        wait_stop "$LIVE_AP/pidfile" 5

        # Cycle 2
        nfcapd -p "$PORT_AP" -4 -w "$LIVE_AP" -D \
               -P "$LIVE_AP/pidfile" -I append -t 3600 -v 0 >/dev/null 2>&1
        sleep 1
        nfreplay -r "$DUMMY_NF" -v 9 -H 127.0.0.1 -p "$PORT_AP" >/dev/null 2>&1
        sleep 1
        kill -TERM "$(cat "$LIVE_AP/pidfile" 2>/dev/null)" 2>/dev/null || true
        wait_stop "$LIVE_AP/pidfile" 5

        if [ -f "$LIVE_AP/pidfile" ]; then
            fail "live_append_rename: nfcapd did not terminate on second cycle"
        else
            ap_total=0
            for apf in "$LIVE_AP"/nfcapd.*; do
                [ -f "$apf" ] || continue
                apc=$(count_flows "$apf")
                ap_total=$(( ap_total + ${apc:-0} ))
            done
            ap_expected=$(( LIVE_V9_FLOWS * 2 ))
            if [ "$ap_expected" -gt 0 ] && [ "$ap_total" -eq "$ap_expected" ]; then
                pass "live_append_rename: $ap_total flows across 2 cycles"
            elif [ "$ap_expected" -eq 0 ]; then
                skip "live_append_rename: v9 baseline was 0, cannot validate total"
            else
                fail "live_append_rename: expected $ap_expected flows, got $ap_total"
            fi
        fi
    fi
fi   # nfreplay / dummy_flows.nf available

# =============================================================================
# 7. Memory / allocator guard checks (pcap mode)
# =============================================================================
echo ""
echo "── memory guard checks ──────────────────────────────────────────────────"

if [ "$HAS_PCAP" -eq 0 ]; then
    for _t in memck_flows_v5_unsamp memck_flows_v9_unsamp memck_flows_ipfix_unsamp \
              memck_nsel memck_CGNAT-ifvrf; do
        skip "$_t: --enable-readpcap not compiled in"
    done
else
    # Activate platform-specific allocator diagnostics.
    export MALLOC_OPTIONS=CFGJS         # OpenBSD
    export MallocGuardEdges=1           # macOS
    export MallocScribble=1
    export MallocErrorAbort=1
    export MallocCorruptionAbort=1

    for pcap in \
        "$TESTDATA/flows_v5_unsamp.pcap" \
        "$TESTDATA/flows_v9_unsamp.pcap" \
        "$TESTDATA/flows_ipfix_unsamp.pcap" \
        "$TESTDATA/nsel.pcap" \
        "$TESTDATA/CGNAT-ifvrf.pcap"; do

        mname="memck_$(basename "$pcap" .pcap)"
        md="$WORKDIR/$mname"
        mkdir -p "$md"
        if nfcapd -f "$pcap" -w "$md" -I memck -v 0 >/dev/null 2>&1; then
            pass "$mname"
        else
            fail "$mname: nfcapd crashed or returned non-zero under memory guards"
        fi
    done

    unset MALLOC_OPTIONS MallocGuardEdges MallocScribble MallocErrorAbort \
          MallocCorruptionAbort
fi

summary
