name: C/C++ CI

on:
  push:
    branches: 
      - "master"
      - "devel_1.8.x"
  pull_request:
    branches: 
      - "master"
      - "devel_1.8.x"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libpcap-dev

    - name: Bootstrap
      run: sh bootstrap

    # This step runs DIFFERENT arguments based on the active branch
    - name: Configure
      run: |
        if [ "${{ github.ref_name }}" = "master" ]; then
          echo "Configuring for master branch..."
          ./configure --enable-sflow --enable-maxmind --enable-tor --enable-ja4 --enable-nfpcapd
        elif [ "${{ github.ref_name }}" = "devel_1.8.x" ]; then
          echo "Configuring for devel_1.8.x branch..."
          ./configure --enable-nfpcapd --enable-ja4
        else
          echo "Fallback configuration for other branches/pull requests..."
          ./configure --enable-sflow --enable-maxmind --enable-tor --enable-nfpcapd
        fi

    - name: Make
      run: make

    - name: Run tests
      run: make check

