name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libpcap-dev

    - name: Bootstrap
      run: sh bootstrap

    - name: Configure
      run: ./configure --enable-sflow --enable-maxmind --enable-tor --enable-nfpcapd

    - name: Make
      run: make

    - name: Run tests
      run: make check

